name: ðŸ”Ž Code Safety
run-name: Running Code Safety for ${{ github.ref }} on ${{ github.event_name }} ðŸ”Ž
on:
  pull_request:
    branches:
      - main
jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - run: uv run ruff check .

  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - run: uv run ruff format --check .

  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - run: uv run pyright

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - run: uv run pytest